export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST = 'REMOVE_POST';

export const CREATE_POST_INIT = 'CREATE_POST_INIT';
export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_FINISH = 'EDIT_POST_FINISH';

export const GET_POSTS_CATEGORY_INIT = 'GET_POSTS_CATEGORY_INIT';
export const GET_POSTS_CATEGORY_START = 'GET_POSTS_CATEGORY_START';
export const GET_POSTS_CATEGORY_SUCCESS = 'GET_POSTS_CATEGORY_SUCCESS';
export const GET_POSTS_CATEGORY_FAIL = 'GET_POSTS_CATEGORY_FAIL';

export const GET_POPULAR_START = 'GET_POPULAR_START';
export const GET_POPULAR_SUCCESS = 'GET_POPULAR_SUCCESS';
export const GET_POPULAR_FAIL = 'GET_POPULAR_FAIL';

export const SET_POST_LIKE_SUCCESS = 'SET_POST_LIKE_SUCCESS';
export const SET_POST_LIKE_FAIL = 'SET_POST_LIKE_FAIL';

export const SET_AUDIO_LISTEN_SUCCESS = 'SET_AUDIO_LISTEN_SUCCESS';
export const SET_AUDIO_LISTEN_FAIL = 'SET_AUDIO_LISTEN_FAIL';

export const FILTER = 'FILTER';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_COMMENT_START = 'SET_COMMENT_START';
export const SET_COMMENT_SUCCESS = 'SET_COMMENT_SUCCESS';
export const SET_COMMENT_FAIL = 'SET_COMMENT_FAIL';
